const data = [
    {
        "id": 12,
        "brandName": "bmw",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/BMW.png",
        "description": "BMW is German well-known automobile company, the word BMW stands for Bayerische Motoren Werke AG in German. Whereas in English, Bavarian Motor Works. BMW is known for manufacturing quality cars and motorcycles.\nBMW started its motorcycle manufacturing in 1921 and later it merged with Bayerische Flugzeugwerke. The company inherited Helios motorcycle and 02 stroke small motorized bicycle called Friz. BMW introduced R32 motorcycle, which is equipped 486 cc engine with 8.5 hp with a top speed of 95 to 100 km/h. \n\nBMW introduced recirculating wet sump oil system with drip feed to roller bearing. Whereas other manufacturers total loss oiling system.\n",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "BMW New Bikes in Pakistan, Get yourself updated from the latest super bike news and videos reviews about BMW New Bikes in Pakistan on ebike.pk.",
        "focus_keyword": "bmw",
        "createdAt": "2018-12-14T12:35:34.243Z",
        "updatedAt": "2019-11-07T12:11:38.285Z"
    },
    {
        "id": 10,
        "brandName": "zxmco",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_80,dpr_auto/v1540624361/bike_brands/Zxmco.png",
        "description": "ZXMCO Motorcycle, a renowned motorcycle brand is introduced by Abdul Samad Group. The company started its motorcycle production in August 2004. The company introduced various models from 70cc to 250cc motorcycle segment.\nZXMCO has focused on providing reliable motorcycles to its customers. Therefore, they developed strong 03 S dealer network throughout Pakistan.\n",
        "vediourl": null,
        "meta_title": "ZXMCO Motorcycles in Pakistan | Abdul Samad Group | ebike.pk",
        "meta_description": "ZXMCO New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about ZXMCO New Bikes in Pakistan.",
        "focus_keyword": "zxmco motorcycles",
        "createdAt": "2018-12-14T12:34:10.413Z",
        "updatedAt": "2019-11-12T12:09:52.597Z"
    },
    {
        "id": 24,
        "brandName": "hi_speed",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/High_speed.jpg",
        "description": "Raazy Motor Industries, the manufacturers of Hi Speed Motorcycles established in 2004. The company is engaged in manufacturing of 70cc, 100cc, 125cc & 150cc motorcycles. Moreover, the company also manufactures 150cc cargo loaders. Hi Speed 150cc is the premier brand of Raazy Motors. ",
        "vediourl": null,
        "meta_title": "Hi Speed Motorcycles | Razzy Motors Industries Pvt. Ltd | ebike.pk",
        "meta_description": "Hi-Speed New Bikes in Pakistan, Get yourself updated from the latest news and video reviews about Hi Speed New Bikes in Pakistan.",
        "focus_keyword": "hi speed",
        "createdAt": "2018-12-14T12:44:07.891Z",
        "updatedAt": "2019-11-19T11:17:08.413Z"
    },
    {
        "id": 2,
        "brandName": "kawasaki",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_30,q_auto,w_50,dpr_auto/v1540624358/bike_brands/kawasaki.png",
        "description": "Kawasaki Heavy Industries Limited is leading Japanese Conglomerate engage in manufacturing of heavy equipment, aerospace, defense equipment, motorcycles, rolling stock and ships, industrial robots, gas turbines and boilers. Kawasaki was formed by Shozo Kawasaki on October 15, 1896. The Kawasaki headquarters is situated in Chuo-ku, kobe & Minato, Tokyo.  ",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Kawasaki New Bikes in Pakistan, Get yourself updated from the latest sportbike news and videos reviews about Kawasaki New Bikes on ebike.pk.",
        "focus_keyword": "kawasaki",
        "createdAt": "2018-12-14T12:19:27.265Z",
        "updatedAt": "2019-11-07T12:12:02.196Z"
    },
    {
        "id": 15,
        "brandName": "metro",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/metro.jpg",
        "description": "",
        "vediourl": null,
        "meta_title": "Metro Motorcycle Manufacturer | Ohad Motors | ebike.pk",
        "meta_description": "Metro New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Metro New Bikes in Pakistan.",
        "focus_keyword": "metro motorcycle",
        "createdAt": "2018-12-14T12:37:21.982Z",
        "updatedAt": "2019-11-12T12:10:21.381Z"
    },
    {
        "id": 9,
        "brandName": "ghani",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624357/bike_brands/Ghani.png",
        "description": "\nGhani Automobile Limited, a public listed company Pakistan Stock Exchange started its operations in 2005. Ghani Automobile is engaged in assembling 70 to 100cc motorcycles. The factory is situated at Multan Road, Whereas the office of the company is situated at Model Town Lahore.\n\nThe objective of the company is to provide the economical and quality motorcycles to its customers in 70cc and 100cc range. So far they are successful in providing the quality motorbikes to their customers. Ghani has sizeable market share in Punjab.\n",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Ghani New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Ghani New Bikes in Pakistan.",
        "focus_keyword": "ghani motorcycles",
        "createdAt": "2018-12-14T12:33:32.989Z",
        "updatedAt": "2019-11-13T09:32:06.305Z"
    },
    {
        "id": 14,
        "brandName": "ducati",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Ducati.jpg",
        "description": "Ducati Motor Holding S.P.A, an Italian manufacturing motorcycle division headquartered in Bologna, Italy. Ducati is owned by German automotive manufacturer Audi through its Italian Subsidary Lamborghini.\nDucati has been known for manufacturing quality motorcycles with four stroke 90 v twin engines. As  Ducati refers this configuration as L-twin mainly because one cylinder is vertical whereas the other is horizontal, making it look like a letter \"L\". Today Ducati has been regarded as the dominant performance motorcycle in the world due to desmodromic valve design.\n\nThe chief designer of Ducati motorcycles in 1950’s was Fabio Taglioni. These designs ranges from small single cylinder machines. Those machines were successful in Italian Street Races.\n",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Ducati Sport New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Ducati Sport New Bikes in Pakistan.",
        "focus_keyword": "ducati bikes",
        "createdAt": "2018-12-14T12:36:42.910Z",
        "updatedAt": "2019-11-13T09:32:59.700Z"
    },
    {
        "id": 38,
        "brandName": "sport",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Sports_logo.jpg",
        "description": "",
        "vediourl": null,
        "meta_title": null,
        "meta_description": "Sport New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Sport New Bikes in Pakistan.",
        "focus_keyword": null,
        "createdAt": "2019-01-28T06:17:44.216Z",
        "updatedAt": "2019-11-15T10:22:19.154Z"
    },
    {
        "id": 39,
        "brandName": "ktm",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1548851462/ktm.jpg",
        "description": "KTM known for its off road motorcycles (supermoto, endure and motocross). However, later it has expanded to street motorcycles and started manufacturing sports cars as well.\nKTM AG is an Austrian firm established in 1932 and it is owned by KTM Industries AG & Bajaj Auto India. KTM has been the largest motorbike manufacturer in Europe for 04 years since 2012. KTM is one of the leading off-road motorcycle manufacturers of the world. \n",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "KTM New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about KTM New Bikes in Pakistan.",
        "focus_keyword": "ktm motorcycles",
        "createdAt": "2019-01-30T12:33:13.275Z",
        "updatedAt": "2019-11-08T11:33:43.786Z"
    },
    {
        "id": 37,
        "brandName": "aprilia",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_80,dpr_auto/v1540624357/bike_brands/Aprilia.png",
        "description": "",
        "vediourl": null,
        "meta_title": null,
        "meta_description": "Aprilia New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Aprilia New Bikes in Pakistan.",
        "focus_keyword": null,
        "createdAt": "2019-01-18T07:04:00.195Z",
        "updatedAt": "2019-11-08T11:34:53.820Z"
    },
    {
        "id": 32,
        "brandName": "china",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1547794602/bike_brands/Capture.png",
        "description": "",
        "vediourl": null,
        "meta_title": null,
        "meta_description": "All Types of New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about All Types of New Bikes in Pakistan.",
        "focus_keyword": null,
        "createdAt": "2019-01-12T17:22:44.966Z",
        "updatedAt": "2019-11-15T10:21:57.301Z"
    },
    {
        "id": 22,
        "brandName": "ravi",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540640213/bike_brands/Ravi.jpg",
        "description": "",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Ravi New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Ravi New Bikes in Pakistan.",
        "focus_keyword": "ravi motorcycle",
        "createdAt": "2018-12-14T12:42:24.334Z",
        "updatedAt": "2019-11-14T13:03:33.010Z"
    },
    {
        "id": 11,
        "brandName": "treet",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_30,q_auto,w_60,dpr_auto/v1540624360/bike_brands/treat_bike_logo.png",
        "description": "Ali Group, the brain child of Sir Syed Maratib Ali who expanded its agricultural business in to industrial and trading business. The history of this group started prior to the indo-pak partition. Soon after the partition the Treet Corporation started its business operations in 1952. \nTreet Corporation, a public listed company engaged in the manufacturing of various kind of razors and blades since decades. Treet has been recognized for its quality razors and blades.\n\nThe rising demand of motorcycles in the last one and a half decade has forced this group to launch economical motorcycles. The company has introduced wide range of 70cc motorcycles with self-start option, 100cc and three wheelers for the loading purpose.\n\nIt is worth mentioning here that Packages Ltd, IGI Insurance, Loads Limited and Liaqat National is also part of this group.\n",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Treet New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Treet New Bikes in Pakistan.",
        "focus_keyword": "treet motorcycles",
        "createdAt": "2018-12-14T12:35:00.417Z",
        "updatedAt": "2019-11-14T13:04:21.340Z"
    },
    {
        "id": 25,
        "brandName": "crown",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624357/bike_brands/Crown.jpg",
        "description": "Lifan group entered into an agreement with Crown group Karachi with an objective to get a sizeable market share in the motorcycle industry of Pakistan. The Joint Venture between these two has achieved remarkable position of CRLF products within two years. In addition to this the Crown group has introduced its motorcycles in 2005 with an objective to meet a growing demand of motorcycles.\n\nCrown Motorcycles are being made from CRLF products. The company manufactures 85,000 motorcycles per annum from their plant situated at Sadiqabad, Punjab. Crown Motorcycles plant is equipped with state of the art machines.\n\n",
        "vediourl": null,
        "meta_title": "Crown Bike in Pakistan Pakistan | Crown Motor Company Ltd |ebike.pk",
        "meta_description": "Crown bike is introduced by Crown & Lifan in Pakistan. Crown bike is available in 70cc, 100cc & 150cc. Crown Lifan is mainly due to its motorcycle parts.",
        "focus_keyword": "crown bike",
        "createdAt": "2018-12-14T12:45:16.674Z",
        "updatedAt": "2019-04-03T10:50:35.014Z"
    },
    {
        "id": 8,
        "brandName": "united",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624361/bike_brands/united.jpg",
        "description": "United Auto Industries, the manufacturer of United Motorcycles is the brainchild of Mr. Sanaullah Chaudhary, who established this company in 1999. Now United Motorcycles become the 2nd largest selling motorcycle brand in Pakistan.\nInitially company started manufacturing Autorickshaws with a brand name of United. However, the growing demand of 02 wheelers had forced the management to enter in this lucrative business. United Auto Industries plant is situated at an area 720,000 Sq.ft approx  in 1-km off Kot Radha Kishan Road, Multan Road, Bhai Pheru Lahore. The current production capacity of a plant is 450,000 unit. The company is striving hard in providing quality motorcycles, which is in accordance with PQSCA (Pakistan Quality Standard Certification Association) to their customers.\nRecently United Auto Industries started assembling economical 800 – 1000 cc cars, adding a good option for the car users.\n",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "United New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about United New Bikes in Pakistan.",
        "focus_keyword": "united motorcycle",
        "createdAt": "2018-12-14T12:32:53.079Z",
        "updatedAt": "2019-11-19T11:18:12.453Z"
    },
    {
        "id": 7,
        "brandName": "yamaha",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624361/bike_brands/Yamaha.png",
        "description": "Yamaha Motors entered into Pakistani market in 2013 with an aim to provide the quality motorcycles in 125cc segment. Earlier the Yamaha brand was represented and marketed by Dawood Group in Pakistan. \nInitially Yamaha Motors invested U$ 180 Mn on plant and machinery and setup their plant at Port Qasim, near Karachi. The company has introduced its 03 models in 125cc range i.e. YBR 125, YBR 125G and YB 125Z meeting its international standards. Yamaha focusing on developing its strong 03 S (Sales, Service & Spares) dealer network in Pakistan.\n",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Yamaha New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Yamaha New Bikes YBR 125, YB125z and YBR 125G.",
        "focus_keyword": "yamaha",
        "createdAt": "2018-12-14T12:25:19.604Z",
        "updatedAt": "2019-11-06T07:45:21.345Z"
    },
    {
        "id": 35,
        "brandName": "harley_davidson",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Harley_Davidson.png",
        "description": "Harley Davidson, an American brand known for manufacturing cruiser and chopper motorbikes. The company was founded by William S. Harley, Arthur Davidson, Walter Davidson, William A. Davidson in 1903. Harley Davidson factories located in Kansas City, Wisconsin, Milwaukee, Pennsylvania, York, Manaus, Brazil, Bawal, India",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Harley Davidson Cruiser/Choppers Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Harley Davidson Cruiser/Choppers Bikes in Pakistan on ebike.pk.",
        "focus_keyword": "harley davidson",
        "createdAt": "2019-01-18T07:01:30.883Z",
        "updatedAt": "2019-11-07T10:54:55.016Z"
    },
    {
        "id": 36,
        "brandName": "derbi",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_40,q_auto,w_70,dpr_auto/v1540624357/bike_brands/Derbi.jpg",
        "description": "Derbi Pakistan is a project of Ravi Automobile & Piaggio & C.S.P.A (Italy). The reason for this project is to introduce the quality sporty street bikes to the young generation of Pakistan. The arrival of Derbi in 150cc category has provided an opportunity for the young riders to get the solution for road riding, off-road and racing\nInitially Derbi Pakistan introduces 2 models in 150cc category\n\n1. DERBI STX (Sporty and Aggressive Design)\n2. DERBI ETX (Enduro motorcycle, the new shining star)\n",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Derbi New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Derbi New Bikes in Pakistan.",
        "focus_keyword": "derbi",
        "createdAt": "2019-01-18T07:02:24.966Z",
        "updatedAt": "2019-11-08T11:34:19.710Z"
    },
    {
        "id": 19,
        "brandName": "road_prince",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_80,dpr_auto/v1540624358/bike_brands/Road_Prince.jpg",
        "description": "Omega Industries, the firm behind Road Prince motorcycles started its journey a decade ago.  It is the brain child of Mr. Tanveer Ahmed, who played a key role in the success of this brand. The objective of the company is to provide the quality motorcycles with complete back up support. So far they are successful in making Road Prince the 3rd largest selling motorcycle brand of Pakistan.\nOmega Industries is offering 70cc, 110cc, 125cc, 150cc, 250cc & loader trucks. The famous brand Wego 150 and Robinson 150cc motorcycle make the Road prince brand popular. Both brands are designed in collaboration with Piaggio, Italy. The unique design and durability of Wego and Robinson has forced the bike users to purchase it. In addition to this the company has been focusing on providing the backup support facility to its customers.\n",
        "vediourl": null,
        "meta_title": "Road Prince Motorcycles 2019 | Omega Industries | ebike.pk",
        "meta_description": "Road Prince New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Road Prince New Bikes 70cc, 110cc, 125cc, 150cc and 250cc. Road Prince Wego 150",
        "focus_keyword": "road prince",
        "createdAt": "2018-12-14T12:39:57.026Z",
        "updatedAt": "2019-11-09T09:19:30.605Z"
    },
    {
        "id": 1,
        "brandName": "honda",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
        "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
        "focus_keyword": "honda",
        "createdAt": "2018-12-14T12:18:45.057Z",
        "updatedAt": "2019-11-06T07:43:18.264Z"
    },
    {
        "id": 16,
        "brandName": "unique",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624360/bike_brands/unique.jpg",
        "description": "Unique motorcycles established in 2004, is a recent but a widely known and well reputed company. With their sole purpose to emerge as the market leader in the industry, Unique has been successful in their rapid and massive expansion in the country. Being one of Pakistan’s most known and loved brand it has now gained the trust and adoration of its customers and has admitted to it being the only reason for their huge success.\nThe company was started with a mean to encourage and satisfy the requirements of the market and to set a high standard of expectations. It has effectively conveyed reasonable items to the large group of its customer base and against all odds they promise on never compromising on their customer service. The company envisions, to not only become the number one brand in the motorcycle industry but it also strongly believes in an empowered society where there are various opportunities for a common individual.\nWhen Unique states its central goal it maintains straightforwardness, and claims it to be the main in the business. Keeping aside their business, Unique motorcycles feels like it is a need to change the general public by making lives simple and by satisfying their Corporate Social Responsibilities as an organization. They trust that their clients are the main ones who help them in accomplishing their objectives and along these lines they make sure to prioritize their customer needs. \nBesides selling in Pakistan, Unique has other customer bases too. They make sure that the quality and services of the motorcycles that are sent abroad are not compromised. The company assures that they take their customers very seriously be it from countries like Kenya, Sri Lanka, Bangladesh, Saudi Arabia or Egypt to which they deliver via their wheeler loading vans. It is undoubtedly remarkable how Unique has spread in the international waters and is aiming to expand even further. The list of the countries they sell too is growing as are they, as a business\n",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Unique New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Unique New Bikes UD 70cc, UD 125 and Crazer 150.",
        "focus_keyword": "unique motorcycle",
        "createdAt": "2018-12-14T12:37:59.933Z",
        "updatedAt": "2019-11-09T09:18:32.109Z"
    },
    {
        "id": 5,
        "brandName": "super_power",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Super_Power.jpg",
        "description": "NJ Auto Industries, manufacturer of Superpower motorcycles started its operation in 2004 with an objective to meet the growing demand of 02 wheelers. N.J Auto Industries has also been involved in manufacturing of Auto Rickshaw.\n\nPresently the company has been assembling 70cc, 100cc, 125cc, 150cc and 250cc motorcycles. Superpower Motorcycles has been engaged with Pakistan Super League (PSL) as a top sponsor of the event. The strong dealer and service network of Superpower Motorcycles make the brand successful. Superpower Motorcycles brand has been selling in Sindh & Balochistan under the umbrella of N.J Auto Industries. Whereas Kausar Automobile Pvt Ltd, the part of Pirani group is selling these motorcycles with  Power Motorcycles brand in KPK & Punjab.\n\n",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Super Power New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Super Power New Bikes SP 70cc, SP125, Sultan and Girls Scooty 150.",
        "focus_keyword": "super power bike",
        "createdAt": "2018-12-14T12:23:32.846Z",
        "updatedAt": "2019-11-09T09:20:33.477Z"
    },
    {
        "id": 20,
        "brandName": "eagle",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540640242/bike_brands/Eagle.jpg",
        "description": "Waqar Shaffi group has been engaged in diversified businesses i.e. polyurethane foam, spring mattresses, auto-parts, packing and insulation material etc. Earlier the group was established by Mian Shaffi and Mr. Ejaz Shaffi in 1974. The group established its Ist cycle tube factory in Karachi and later they diversify their business. The group is also  manufacturing Eagle Motorcycles in Pakistan.",
        "vediourl": null,
        "meta_title": "Eagle Bikes in Pakistan 2019 | ebike.pk",
        "meta_description": "Eagle New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Eagle New Bikes in Pakistan.",
        "focus_keyword": "eagle bikes",
        "createdAt": "2018-12-14T12:41:17.186Z",
        "updatedAt": "2019-11-14T13:04:50.182Z"
    },
    {
        "id": 6,
        "brandName": "suzuki",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
        "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
        "focus_keyword": "suzuki bikes",
        "createdAt": "2018-12-14T12:24:37.544Z",
        "updatedAt": "2019-11-19T11:16:39.339Z"
    },
    {
        "id": 41,
        "brandName": "benelli",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1582175161/bike_brands/Logo-Benelli-Motorcycles.jpg",
        "description": "",
        "vediourl": null,
        "meta_title": null,
        "meta_description": "Benelli New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Benelli New Bikes in Pakistan.",
        "focus_keyword": null,
        "createdAt": "2019-02-18T05:50:55.299Z",
        "updatedAt": "2020-02-20T05:22:00.926Z"
    },
    {
        "id": 40,
        "brandName": "osaka",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1582176239/bike_brands/OSAKA.png",
        "description": "",
        "vediourl": null,
        "meta_title": "Osaka Motorcycle Manufacturer in Pakistan | Osaka Bikes | ebike.pk",
        "meta_description": "Osaka New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Osaka New Bikes in Pakistan.",
        "focus_keyword": "osaka motorcycle",
        "createdAt": "2019-02-01T10:12:28.158Z",
        "updatedAt": "2020-02-20T05:26:33.615Z"
    },
    {
        "id": 47,
        "brandName": "vespa",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/v1606129162/Vespa_1.jpg",
        "description": "",
        "vediourl": null,
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2020-11-25T08:23:47.573Z",
        "updatedAt": "2020-11-25T09:36:25.047Z"
    },
    {
        "id": 48,
        "brandName": "norton",
        "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,h_50,w_100/v1605954952/bike_brands/Norten_logo.jpg",
        "description": "Norton Mortorcycles",
        "vediourl": null,
        "meta_title": "Norton Mortorcycles",
        "meta_description": "Norton Mortorcycles",
        "focus_keyword": null,
        "createdAt": "2020-11-25T09:33:19.261Z",
        "updatedAt": "2020-11-30T06:52:03.842Z"
    }
]

export default data;

// http://localhost:4000/api/brand/get-brand
