export const initialMechanics = [
    {
        "id": 24,
        "shop_name": "New Madina Autos",
        "brand_id": 1,
        "phone": "03002453355",
        "phone2": "02134714888",
        "address": "A-1414, Phase I, Gulshan- e -Hadeed Karachi.",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 1,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-01-23T11:13:18.920Z",
        "updatedAt": "2019-01-23T11:16:13.492Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    },
    {
        "id": 18,
        "shop_name": "Faisal Automobile",
        "brand_id": 1,
        "phone": "03009286713",
        "phone2": "02132729003",
        "address": "10 Merry Mension Frere Road, Shahrah-e-Liaquat, Saddar, Karachi.",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 1,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-01-23T10:58:47.713Z",
        "updatedAt": "2019-01-23T11:16:15.775Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    },
    {
        "id": 26,
        "shop_name": "Warsi Autos",
        "brand_id": 1,
        "phone": "03332179148",
        "phone2": "",
        "address": "Shop: 96/1, Sector F-5, Lal Market, New, Karachi.",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 1,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-01-23T11:23:10.593Z",
        "updatedAt": "2019-01-23T11:23:29.061Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    },
    {
        "id": 25,
        "shop_name": "New Khursheed Autos",
        "brand_id": 1,
        "phone": "03362520032",
        "phone2": "",
        "address": "Shop No: 34, KDA Lal Flat, Block -10-A, Rashid Minhas Road Gulshan-e- Iqbal Karachi.",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 1,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-01-23T11:19:44.101Z",
        "updatedAt": "2019-01-23T11:23:30.284Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    }
]

export const initialDealers = [
    {
        "id": 179,
        "shop_name": "Kohistan Honda Agency",
        "brand_id": 1,
        "phone": "03445468812",
        "phone2": "",
        "address": "Near govt commerce collage,bank of khyber, Punjab\n",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 660,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-01-18T12:15:43.500Z",
        "updatedAt": "2019-01-18T13:32:03.466Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 660,
            "city_name": "Punjab",
            "createdAt": "2019-01-12T12:43:40.452Z",
            "updatedAt": "2019-01-12T12:43:40.452Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    },
    {
        "id": 210,
        "shop_name": "New Rehman Autos",
        "brand_id": 1,
        "phone": "03006400328",
        "phone2": " 055-3256125",
        "address": "Main Deen Plaza, GT Road, Gujranwala.\n",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 9,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-01-19T11:19:26.214Z",
        "updatedAt": "2019-01-19T11:24:05.066Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 9,
            "city_name": "Gujranwala",
            "createdAt": "2018-11-08T16:23:32.571Z",
            "updatedAt": "2018-11-08T16:23:32.571Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    },
    {
        "id": 178,
        "shop_name": "Kirplani Motors",
        "brand_id": 1,
        "phone": "03332318240",
        "phone2": "02134480080",
        "address": "Gadap City, Gadap Town, Karachi.",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 1,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-01-18T12:14:40.138Z",
        "updatedAt": "2019-01-18T13:32:01.186Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    },
    {
        "id": 793,
        "shop_name": "Zob Honda Centre",
        "brand_id": 1,
        "phone": "3022000616",
        "phone2": "",
        "address": "Doctor Khuda-e-Dad Road, Zhob",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 36,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-02-12T07:21:29.486Z",
        "updatedAt": "2019-02-12T12:24:12.162Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 36,
            "city_name": "Zhob",
            "createdAt": "2018-11-08T16:28:44.619Z",
            "updatedAt": "2018-11-08T16:28:44.619Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    }
]

