let bikesDataArr = [
    {
        "id": 37,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki GS 150 ",
        "description": "<h2>Suzuki GS 150</h2><p><strong>Suzuki GS 150&nbsp;</strong>is the one of the successful tour motorcycles in Pakistan This is claimed as the most powerful bike in the country. Its power comes up from the sophisticated and advanced technology. The <a href=\"https://www.ebike.pk/new-bikes/suzuki\">Suzuki</a> GS 150 engine gives you the pleasure of heavy power while on the go. Pak Suzuki has already made a good reputation as it is the best 4-stroke bikes in the country. Moreover, there are some other reasons as well that make it an accomplished bike.</p><p>Also Read: <a href=\"https://www.ebike.pk/new-bikes/suzuki/suzuki-gixxer-150/18\">Suzuki Gixxer 150</a></p><p>Moreover, it has always been a center of attraction due to the features and specifications it has to offer. One of the most prominent features of Suzuki GS 150 bike is the self start system. Moreover, it also has a kick start system. The energetic engine performance is also loved by the youth to some extent. Now, let&#39;s have a look at the qualities that the new Suzuki GS 150 has.</p><p>Moreover, the <strong>Suzuki GS 150</strong> 2020 offers the users a 5-speed transmission system, which is mostly in cars, or notably four-wheeler vehicles. This contributes a big deal to the quality and comfort in drive. This increases the speed of the Suzuki GS 150 in the flick of an eye, not even making the rider realize about it.&nbsp;</p><p>The design of the <strong>Suzuki GS 150&nbsp;</strong>2020 is quite unique and offers a lot of attraction. It also has eye-catching graphics including the fuel tank, side covers, and other body parts. The seat style and other body parts make the motorcycle comfortable. This not only supports the rider but also one riding pillion.</p><p>Moreover, this will help people going for a very long drive on Suzuki 150. They will not feel tired and stay fresh after covering a distance of hundreds of kilometers. The powerful shock absorbers will not affect your body even when driving on a very bumpy road.</p><p>The rear tyre of the Suzuki GS 150 bike has been broadened, which contribute a lot to the increase in the road grip. The confidence of the rider will also increase when riding even on slippery and rough surfaces. Furthermore, this minimizes the chances of accidents.</p><p>The complete range of <a href=\"https://www.ebike.pk/used-bikes/bike-by-brand/suzuki/6\">Suzuki used bikes </a>available for sale in Pakistan.</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 266000,
        "engine": "4-Stroke Single Cylinder Air Cooled",
        "boreAndStroke": "57.0 x 56.8 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Kick & Electric Start",
        "dimention": "1900",
        "petrolCapacity": "12 Ltr",
        "displacement": "150cc",
        "compressionRatio": "9.2:1",
        "transmission": "5-speed",
        "frame": "Backbone System",
        "groundClearance": "155mm",
        "tyreBack": "3.0 – 18",
        "tyreFront": "2.75 – 18",
        "dryWeight": "116 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604639380/blogs/pbvpk88tiozr27fep8nu.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-gs-150",
        "videoUrl": "https://youtu.be/9artkNg_DGI",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-12T05:46:50.399Z",
        "updatedAt": "2023-01-30T07:06:44.828Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 23,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki Sprinter ECO",
        "description": "<p>Suzuki Sprinter ECO</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 0,
        "engine": "4-Stroke Single Cylinder Air Cooled",
        "boreAndStroke": "53.5 x 48.8 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Kick Start",
        "dimention": "1900",
        "petrolCapacity": "9 L",
        "displacement": "109 cc",
        "compressionRatio": "9.6:1",
        "transmission": "4-speed",
        "frame": "Backbone Type",
        "groundClearance": "150 mm",
        "tyreBack": "2.75 - 18",
        "tyreFront": "2.25 - 18",
        "dryWeight": "91 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604639746/blogs/evqb7s8tukkb9kor8got.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-sprinter-eco",
        "videoUrl": "https://www.youtube.com/watch?v=lLEIr3DlTNg",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-11T11:56:01.237Z",
        "updatedAt": "2021-08-02T07:30:32.258Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 38,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki Bandit ",
        "description": "<p>Suzuki Bandit</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 0,
        "engine": "4- Stroke DOHC 4 Cylinder; Air Cooled",
        "boreAndStroke": "65.5 x 48.7 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Electric Start",
        "dimention": "2145",
        "petrolCapacity": "19 L",
        "displacement": "656 cc",
        "compressionRatio": "11.5:1",
        "transmission": "6-speed",
        "frame": "Semi Double Cradle",
        "groundClearance": "135 mm",
        "tyreBack": "6.3 – 17",
        "tyreFront": "4.7 – 17",
        "dryWeight": "218 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604639311/blogs/oxxnkxlzqrtze7qtzklb.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-bandit",
        "videoUrl": "https://youtu.be/QW6UNuIgHf4",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-12T05:49:49.701Z",
        "updatedAt": "2021-08-02T07:29:17.010Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 36,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki GD 110",
        "description": "<p>Suzuki GD 110</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 0,
        "engine": "4-Stroke Single Cylinder Air Cooled",
        "boreAndStroke": "51.0 x 55.2 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Kick Start",
        "dimention": "\t1900",
        "petrolCapacity": "9 Ltr",
        "displacement": "113 cc",
        "compressionRatio": "9.5:1",
        "transmission": "4-speed",
        "frame": "Backbone Type",
        "groundClearance": "140 mm",
        "tyreBack": "2.75 – 17",
        "tyreFront": "2.5 – 17",
        "dryWeight": "108 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604639650/blogs/ywg5oaoz8x78snxeuog6.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-gd-110",
        "videoUrl": "https://youtu.be/fGAa2_tGjs8",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-12T05:43:14.470Z",
        "updatedAt": "2021-08-02T07:30:14.239Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 17,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki Hayabusa",
        "description": "<h2>Suzuki Hayabusa</h2><p dir=\"ltr\"><strong>Suzuki Hayabusa</strong> is the top of the line ultimate sport bike. Just a twist at the throttle and the bike unleashes its roaring power. The light weight and rigid twin-spar aluminum frame and state-of-the-art suspension provides great performance, handling and amazing control to ensure a smooth riding experience. The overall dynamics of the bike helps it glide through the roads.</p><p dir=\"ltr\">Also Read: <a href=\"https://www.ebike.pk/new-bikes/ducati/ducati-diavel-1260s/85\">Ducati Diavel 1260S</a></p><p dir=\"ltr\">Suzuki Hayabusa comes in different schemes, the Candy daring red or the Metallic Thunder paint schemes. Both come &nbsp;with their contrasting Hayabusa Kanji symbol along with matching wheels. Other then that the powerful 1340cc four-cylinder DOHC engine along with the advanced EFI system brings out the best of the hayabusa and puts it at top of its class. Hayabusa uses state of the art technology and lets the rider choose the ride mode by its S-DMS where the rider can choose his prefered mode to get a better experience of the road.&nbsp;</p><p dir=\"ltr\">The body uses twin-star aluminum alloy frames with castings and extrusions to produce a balanced lightweight. On the front it uses KYB cartridge forks &nbsp;and on the rear a single shock absorber to overcome all minor and major hurdles on the road. In addition to this details have been given to passenger foot peg brackets,muffler and control brackets. Also a variety of accessories have been made available for hayabusa owners making <strong>Suzuki Hayabusa</strong> on the wishlist of every motorcycle enthusiast.</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 0,
        "engine": "DOHC 16 Valve; 4-Cylinder; Liquid Cooled",
        "boreAndStroke": "81 x 65 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Electric",
        "dimention": "2190",
        "petrolCapacity": "20 L",
        "displacement": "1340 cc",
        "compressionRatio": "12.5:1",
        "transmission": "6-speed",
        "frame": "Twin Spar",
        "groundClearance": "120 mm",
        "tyreBack": "7.5 - 17",
        "tyreFront": "4.7 - 17",
        "dryWeight": "220 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1580208336/new-bikes/mdwwfdirbiyyrkvbzrie.jpg",
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1580208345/new-bikes/bnngowajr3aga4jvvzrn.jpg",
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1580208351/new-bikes/ss8s475bw98gatdrjmsh.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-hayabusa",
        "videoUrl": "https://youtu.be/md7JCGuvG4o",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-11T11:13:52.682Z",
        "updatedAt": "2021-08-02T07:32:28.263Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 18,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki Gixxer 150",
        "description": "<h2>Suzuki Gixxer</h2><p><strong>Suzuki Gixxer,</strong> the street sportbike 2020 has been introduced in Metallic Triton Blue, Metallic Red, and Glass Sparkle Black. Gixxer SF Sport is powered by SEP ultra-light and robust 155cc engine with a fuel injection system. It has <a href=\"https://www.motogp.com/\">Moto GP</a> aerodynamic rear and front disc brakes with adjustable rear mono shock suspension.</p><p>Also, Read <a href=\"https://www.ebike.pk/new-bikes/unique/unique-crazer-ud-150/60\">Unique Crazer 150</a></p><p><strong>Suzuki Gixxer&nbsp;</strong>has aerodynamic sport fairing, with stylish LED tail lamp, aluminum muffler cover and smart digital instrumentation with gear position and rpm indicator option. &nbsp;</p><p>Find complete range of <a href=\"https://www.ebike.pk/used-bikes/bike-by-brand/suzuki/6\">Suzuki Used Bikes</a> on ebike.pk.</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 599000,
        "engine": "4-Stroke, 1-Cylinder, Air-cooled",
        "boreAndStroke": "56.0 x 62.9 mm",
        "clutch": "Multi-plate",
        "starting": "Electric/Kick",
        "dimention": "2050",
        "petrolCapacity": "12 L",
        "displacement": "155 cc",
        "compressionRatio": "9:1",
        "transmission": "5-speed",
        "frame": "Semi Double Cradle",
        "groundClearance": "160 mm",
        "tyreBack": "140 - 60",
        "tyreFront": "100 - 80",
        "dryWeight": "130 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604639959/blogs/hoxv1aoakcz7icb7yyoy.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-gixxer-150",
        "videoUrl": "https://youtu.be/0btQp7EP7NQ",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-11T11:19:07.864Z",
        "updatedAt": "2021-03-01T08:16:06.839Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 39,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki Intruder",
        "description": "<h2>Suzuki Intruder</h2><p><br></p><p dir=\"ltr\"><strong>Suzuki Intruder&nbsp;</strong>is a new inclusion to the Suzuki family. &nbsp;With its sporty and fashionable look Intruder adds class and elegance in its user. Special considerations were while designing the Intruder every inch and spec of it generates power and style for its user. From its legendary headlamp to its premium backrest special details have been given to Suzuki Intruder.</p><p dir=\"ltr\"><strong>Suzuki Intruder</strong> is 4-stroke, Single cylinder, Air-cooled engine generates smooth friendly torque which gives power to the rider. &nbsp;Intruder stock comes with state of the art technology, showcased in its modern and smart digital instrumentation in which all the necessary details are displayed. Furthermore, Intruder adopts fuel injection tech. It has 6 sensors to calculate the optimum amount of fuel thus enhancing the performance and taking the bike riding experience to the next level.</p><p dir=\"ltr\">Also Read: <a href=\"https://www.ebike.pk/new-bikes/suzuki/suzuki-inazuma/16\">Suzuki Inazuma</a></p><p dir=\"ltr\">Suzuki Intruder&rsquo;s exhaust coupled with compact back-light and the backrest, Intruder gives an &nbsp;exotic view, with its sharp twin exhaust this beauty roars on the streets and catches the attention of everyone nearby. Intruder comes in three colors Metallic matte Titanium silver, Metallic matte black &nbsp;and glass sparkle black. With a very reasonable price <a href=\"https://www.globalsuzuki.com/motorcycle/\">Suzuki I</a>ntruder gives a lot to its rider.&nbsp;</p><p dir=\"ltr\">Get complete range of <a href=\"https://www.ebike.pk/used-bikes/bike-by-brand/suzuki/6\">Used Suzuki Bikes</a> on ebike.pk</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 0,
        "engine": "Liquid cooled four stroke, 45° V-Twin",
        "boreAndStroke": "83.0 x 74.4 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Electric Start",
        "dimention": "2420",
        "petrolCapacity": "15 Ltr",
        "displacement": "850 cc",
        "compressionRatio": "9.4:",
        "transmission": "5-speed",
        "frame": "Semi Double Cradle",
        "groundClearance": "140 mm",
        "tyreBack": "5.5 – 16",
        "tyreFront": "4.3 – 17",
        "dryWeight": "259 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604639284/blogs/nyddfipchoxnd3u7witv.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-intruder",
        "videoUrl": "https://youtu.be/QW6UNuIgHf4",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-12T05:53:17.215Z",
        "updatedAt": "2021-08-02T07:28:10.283Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 16,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki Inazuma",
        "description": "<h2>Suzuki Inazuma</h2><p><br></p><p dir=\"ltr\"><strong>Suzuki Inazuma&nbsp;</strong>has been developed by <a href=\"https://www.ebike.pk/new-bikes/suzuki\">Suzuki</a> in 250cc engine to eliminate the competition. The thought of a low cost and yet extremely powerful bike is no longer a myth. Inazuma comes with its In-line, twin cylinder, 248cc liquid-cooled engine has rider-friendly power characteristics to suit a variety of riding conditions which gives electrifying power to its user.</p><p dir=\"ltr\">Also Read: <a href=\"https://www.ebike.pk/new-bikes/suzuki/suzuki-intruder/39\">Suzuki Intruder</a></p><p dir=\"ltr\">Inazuma is given a modern sporty look, the compact and sleek design adds on to the style of the user. The &nbsp;Electronic Fuel Injection system (EFI) controls the fuel delivery and the ignition timing based upon the riding conditions to improve fuel economy and reduce emissions giving a jaw dropping experience and an efficient mileage.&nbsp;</p><p dir=\"ltr\">Dual head-pipes effectively route the exhaust through a pair of long and low chromed mufflers that are balanced to the side of the rear wheel so the bike and its rider can sore through the roads and highways in style.</p><p dir=\"ltr\"><strong>Suzuki Inazuma</strong> comes in a very affordable price and given the features it offers it is totally worth it. <a href=\"https://www.globalsuzuki.com/motorcycle/\">Suzuki</a> Inazuma is a dream bike for every enthusiast, cheap, economical and up to every other expectation!&nbsp;</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 0,
        "engine": "4- Stroke SOHC 2 Cylinder",
        "boreAndStroke": "53.5 x 55.2 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Electric Start",
        "dimention": "2145\t",
        "petrolCapacity": "13 L\t",
        "displacement": "248 cc",
        "compressionRatio": "11.5:1",
        "transmission": "6-speed",
        "frame": "Semi Double Cradle",
        "groundClearance": "165 mm",
        "tyreBack": "5.5 - 17\t",
        "tyreFront": "4.3 - 17",
        "dryWeight": "183 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1580121119/new-bikes/u3oaxehmgoiubosnl6f6.jpg",
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1580121123/new-bikes/cnexo2mgh1v5a1qukcjf.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-inazuma",
        "videoUrl": "https://youtu.be/wMb2JYyhxH4",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-11T11:05:51.381Z",
        "updatedAt": "2021-08-02T07:28:52.214Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 20,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki GS 150 SE ",
        "description": "<h2>Suzuki GS 150 SE</h2><p><strong>Suzuki GS 150 SE</strong>&nbsp; introduced by Pak <a href=\"https://www.ebike.pk/new-bikes/suzuki\">Suzuki </a>with elegant design and sporty look. The motorcycle is equipped with 04 stroke air cooled OHC engine with electric and kick start option.&nbsp;</p><p>The 12 Ltrs fuel tank capacity of GS 150se makes it convenient &nbsp;for the riders to continue their long journeys and trips without any refueling delays. The eye catching graphics of this motorcycle attracts its users.&nbsp;</p><p>Also Read: <a href=\"https://www.ebike.pk/new-bikes/road_prince/road-prince-wego-150/30\">Road Prince Wego 150</a></p><p>The powerful shock absorbers and comfortable seats gives a comfort to the rider even on long journeys. <strong>Suzuki &nbsp;GS 150 SE&nbsp;</strong>is an ideal choice for the long bike tours and journeys. It is available in black and red color.&nbsp;</p><p>The complete range of <a href=\"https://www.ebike.pk/used-bikes/bike-by-brand/suzuki/6\">Suzuki Used bikes </a>available for sale in Pakistan.</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 0,
        "engine": "4-Stroke Single Cylinder Air Cooled",
        "boreAndStroke": "57.0 x 56.8 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Kick & Electric Start",
        "dimention": "1890",
        "petrolCapacity": "12 L",
        "displacement": "150 cc",
        "compressionRatio": "9.2:1",
        "transmission": "5-speed",
        "frame": "Backbone Type",
        "groundClearance": "155 mm",
        "tyreBack": "3.0 - 18",
        "tyreFront": "2.75 - 18",
        "dryWeight": "116 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604639894/blogs/l6xs8aujavcv8terqjyl.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-gs-150-se",
        "videoUrl": "https://youtu.be/oRLzdXjsATU",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-11T11:35:30.763Z",
        "updatedAt": "2023-01-30T07:08:44.592Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 22,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki GD 110S",
        "description": "<h2>Suzuki GD 110S</h2><p><br></p><p dir=\"ltr\"><strong>Suzuki GD 110S</strong> is a lightweight motorbike of the Suzuki family. GD-110S is an economical solution who seeks thrill and power. Suzuki has always been quick to establish their market in every region they enter and GD 110S is the trump card for Suzuki.</p><p dir=\"ltr\">Also Read: <a href=\"https://www.ebike.pk/new-bikes/suzuki/suzuki-gd-110/36\">Suzuki GD 110</a></p><p dir=\"ltr\">GD110S uses a 4 Stroke, 110cc SOHC Air cooled Engine with Electric &amp; Decompress Kick for Safe &amp; Easy Start. GD 110S comes with an easy self starter. The overall look is a moderate combination of our typical bikes with a sporty bike. Special details have been given to the bike. With a very stylish fuel tank <a href=\"https://www.globalsuzuki.com/\">Suzuki</a> GD110s ensures a reliable journey to the user. Also in addition to the super comfortable suspension any user can ride without any worries about the bumps and bundles of our roads. Stylish fenders are hooked which adds to the beauty of the bike. The bike comes in 3 different colors Black for elegance, red for thrill and adventure and grey for classy attitude.</p><p dir=\"ltr\"><strong>Suzuki GD 110S</strong> has a great design and features. It offers an economical solution to our daily transport and that too with style.</p><p dir=\"ltr\">The complete <a href=\"https://www.ebike.pk/used-bikes/bike-by-cc/110/4\">110cc used bikes</a> range is available on ebike.pk&nbsp;</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 244000,
        "engine": "4-Stroke Single Cylinder Air Cooled",
        "boreAndStroke": "51.0 x 55.2 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Kick Start",
        "dimention": "1900",
        "petrolCapacity": "9 L",
        "displacement": "113 cc",
        "compressionRatio": "9.5:1",
        "transmission": "4-speed",
        "frame": "Backbone Type",
        "groundClearance": "140 mm",
        "tyreBack": "2.75 - 17",
        "tyreFront": "2.5 - 17",
        "dryWeight": "108 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1580120706/new-bikes/k23rohrjqrzm8eso4tqn.jpg",
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1580120710/new-bikes/yxv7jbhfchnozyb2a63y.jpg",
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1580120714/new-bikes/hdjabqvebq6hnyovg9sr.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-gd-110s",
        "videoUrl": "https://www.youtube.com/watch?v=GD0HaMdu0bE&t=135s",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-11T11:49:25.945Z",
        "updatedAt": "2023-01-30T07:05:58.238Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 21,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki GR 150",
        "description": "<p>Suzuki GR 150</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 385000,
        "engine": "4-Stroke Single Cylinder Air Cooled",
        "boreAndStroke": "57 x 58.6 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Kick & Electric Start",
        "dimention": "2055",
        "petrolCapacity": "12.5 L",
        "displacement": "150 cc",
        "compressionRatio": "",
        "transmission": "5-speed",
        "frame": "Diamond",
        "groundClearance": "165 mm",
        "tyreBack": "3.0 - 18",
        "tyreFront": "2.75 - 18",
        "dryWeight": "133 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604639828/blogs/nd6hscxiwf0urhhdr4ug.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-gr-150",
        "videoUrl": "https://youtu.be/lZM_MyOsZq0",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-11T11:43:41.688Z",
        "updatedAt": "2023-01-30T07:07:23.470Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 40,
        "brandId": 6,
        "cityId": 1,
        "title": "Suzuki Inazuma Aegis",
        "description": "<p>Suzuki Inazuma Aegis</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\">Powered by <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\">Froala Editor</a></p>",
        "price": 0,
        "engine": "4- Stroke SOHC 2 Cylinder",
        "boreAndStroke": "53.5 x 55.2 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Electric Start",
        "dimention": "2145",
        "petrolCapacity": "13 L",
        "displacement": "248 cc",
        "compressionRatio": "11.5:1",
        "transmission": "6-speed",
        "frame": "Semi Double Cradle",
        "groundClearance": "165 mm",
        "tyreBack": "5.5 – 17",
        "tyreFront": "4.3 – 17",
        "dryWeight": "183 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604639233/blogs/p5cdkxjazj1hcyjnuhal.jpg"
        ],
        "others": "",
        "bikeUrl": "suzuki-inazuma-aegis",
        "videoUrl": "https://youtu.be/QW6UNuIgHf4",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-12T05:57:07.321Z",
        "updatedAt": "2023-01-30T07:02:05.031Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    }
]

let dealerDataArr = [
    {
        "id": 858,
        "shop_name": "Mehran Suzuki Center",
        "brand_id": 6,
        "phone": "812667011",
        "phone2": "",
        "address": "Mr. Sanaullah Arts School Road, Quetta.",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 5,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-02-15T10:27:15.001Z",
        "updatedAt": "2019-02-15T11:14:16.890Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 5,
            "city_name": "Quetta",
            "createdAt": "2018-11-08T16:20:41.763Z",
            "updatedAt": "2018-11-08T16:20:41.763Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    },
    {
        "id": 399,
        "shop_name": "Razaq Auto Service",
        "brand_id": 6,
        "phone": "03006886129",
        "phone2": "",
        "address": "Near Grid Station Taulama Road, Mian Chunnu.\n",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 450,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-01-26T10:23:05.019Z",
        "updatedAt": "2019-01-26T10:29:05.857Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 450,
            "city_name": "Mian Channu",
            "createdAt": "2019-01-12T11:59:29.977Z",
            "updatedAt": "2019-01-12T11:59:29.977Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    },
    {
        "id": 864,
        "shop_name": "Islam Autos",
        "brand_id": 6,
        "phone": "3347035749",
        "phone2": "0632272166",
        "address": "Bahwali Road, Bahawalpur.",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 11,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-02-15T10:40:33.041Z",
        "updatedAt": "2019-02-15T11:14:56.923Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 11,
            "city_name": "Bahawalpur",
            "createdAt": "2018-11-08T16:23:55.591Z",
            "updatedAt": "2018-11-08T16:23:55.591Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    },
    {
        "id": 402,
        "shop_name": "Wazirabad Suzuki Center",
        "brand_id": 6,
        "phone": "03338802002",
        "phone2": "",
        "address": "Sialkot Road, Wazirabad.\n",
        "uid": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
        "city_id": 652,
        "request_for_featured": false,
        "is_featured": false,
        "is_approved": true,
        "createdAt": "2019-01-26T10:31:44.464Z",
        "updatedAt": "2019-01-26T10:32:04.793Z",
        "bike_brand": {
            "id": 6,
            "brandName": "suzuki",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624359/bike_brands/Suzuki.png",
            "description": "Pak Suzuki is a listed company, established in 1983 as a joint venture between Govt. of Pakistan and Suzuki Motors Japan.  Pak Suzuki hardly face any competition and enjoyed full monopoly.  It is undoubtedly the market leader in automobiles in Pakistan. Pak Suzuki not only assembling cars but also engage in manufacturing of motorcycles mainly  110cc to 150cc range ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Suzuki New Bikes in Pakistan, Get yourself updated from the latest news and videos reviews about Suzuki New Bikes GR 150cc, GS 150, GS150se, GD110, GD, GD 110s and Hayabusa.",
            "focus_keyword": "suzuki bikes",
            "createdAt": "2018-12-14T12:24:37.544Z",
            "updatedAt": "2019-11-19T11:16:39.339Z"
        },
        "city": {
            "id": 652,
            "city_name": "Wazirabad",
            "createdAt": "2019-01-12T12:26:19.836Z",
            "updatedAt": "2019-01-12T12:26:19.836Z"
        },
        "user": {
            "id": "bbbc6ed0-786f-4a4d-bf91-3de5f4dd68dd",
            "userFullName": "faizan",
            "userType": "user",
            "signupType": "email",
            "email": "faizanjunaid780@gmail.com",
            "password": "8bb0cf6eb9b17d0f7d22b456f121257dc1254e1f01665370476383ea776df414",
            "isVerified": true,
            "status": "inactive",
            "last_login": "2019-01-12T04:31:46.073Z",
            "social_uid": null,
            "createdAt": "2019-01-12T08:31:12.778Z",
            "updatedAt": "2019-01-12T08:31:40.369Z"
        }
    }
]

export { dealerDataArr, bikesDataArr };

// http://localhost:4000/api/dealer/dealer-by-brand/25
// http://localhost:4000/api/new-bikes/get-new-bikes-by-brand/
// {
//     "brand": "crown"
// }

