const  BikePriceData = [
    {
        "id": 8,
        "brandId": 1,
        "cityId": 1,
        "title": "Honda CB 250f ",
        "description": "<h2>Honda CB 250F</h2><p dir=\"ltr\"><strong>Honda CB-250f&nbsp;</strong>is currently top notch top of the line production of <a href=\"https://www.ebike.pk/new-bikes/honda\">Atlas Honda Ltd</a>. CB-250f offers it&rsquo;s SOHC (Single Overhead Cam), 4 Valve, Single Cylinder<a href=\"https://www.ebike.pk/used-bikes/bike-by-cc/250/8\">&nbsp;250cc</a> Engine puts it at the throne. It&rsquo;s Sporty &amp; Modern Fuel Tank, 6 Speed Gearbox, Self Start System and Programmed Fuel Injection Technology gives it a sleek and sporty look.</p><p dir=\"ltr\">Also Read &nbsp;<a href=\"https://www.ebike.pk/new-bikes/honda/honda-cg-125s-special-edition/210\">Honda CG125s Special Edition</a></p><p dir=\"ltr\">Honda CB-250f&rsquo;s <a href=\"https://advrider.com/f/threads/twin-shocks-vs-monoshocks.974512/\">Monoshock Swing Arm</a> (back suspension) and Telescopic Fork (Front Suspension) absorbs the traumatizing shocks of any road and ensures a smooth and fun thrilling ride to its user. &nbsp;Honda Cb250f has a 16.5 liter petrol capacity which can be utilized in-case of long trips. Furthermore, Front &amp; Rear Disk Brakes and Durable Alloy Rims with Tubeless Tires gives user a reliable safety assurance.</p><p dir=\"ltr\"><strong>Honda CB-250&nbsp;</strong>stock has Powerful 60/50 W Beam Headlight, Impressive LED supported Tail Light, Completely Digitized Speedometer, Stylish &amp; Aerodynamic Muffler Exhaust to dominate the roads.</p><p dir=\"ltr\">The complete <a href=\"https://www.ebike.pk/used-bikes/bike-by-brand/honda/1\">Honda Used Bikes</a> available for Sale in Pakistan.</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\"> <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\"></a></p>",
        "price": 0,
        "engine": "SOCH, 4 Value, Single Cylinder Engine",
        "boreAndStroke": "71 x 63 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Self Start",
        "dimention": "2065",
        "petrolCapacity": "16.5 Liters",
        "displacement": "249.58 cm3",
        "compressionRatio": "9.6:1",
        "transmission": "6 Speed Gearbox",
        "frame": "Cradle, Steel",
        "groundClearance": "192 mm",
        "tyreBack": "Tubeless 140/70-R 17 M/C (66H)",
        "tyreFront": "Tubeless 110/70-R 17 M/C (54H)",
        "dryWeight": "135 kg",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604561739/blogs/nrxp5wan4gnubaqgksv4.jpg"
        ],
        "others": "",
        "bikeUrl": "honda-cb-250f",
        "videoUrl": "https://youtu.be/o7uzktNBXwA",
        "meta_title": "Honda CB 250f Price in Pakistan 2019, Specs & Pics",
        "meta_description": "Get Honda CB 250f Price in Pakistan 2019, Specs, Pics, feature and video review on ebike.pk. Honda CB 250f sporty model for super bike lovers.",
        "focus_keyword": "honda cb250f 2019",
        "createdAt": "2019-01-10T08:29:15.976Z",
        "updatedAt": "2021-02-23T07:27:45.191Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 2,
        "brandId": 1,
        "cityId": 1,
        "title": "Honda CD 70 Dream",
        "description": "<h2>Honda CD 70 Dream</h2><p><strong>Honda CD 70 Dream</strong> has come up with stylish and sleek look appealing to the young generation. The smooth and comfortable ride of this motorcycle make the rider relaxed even during the long journeys.</p><p>Also Read &nbsp;<a href=\"https://www.ebike.pk/new-bikes/honda/honda-pridor/3\">Honda Pridor 100</a><a href=\"https://www.ebike.pk/new-bikes/honda/honda-cd-70/1\"></a></p><p>Honda CD 70 Dream is equipped with 04 stroke air cooled single cylinder 72cc engine with 04 speed transmission. Honda motorcycles are known due to its reliable quality and re-sale value so is 70 Dream. The dry weight of Honda Dream 70 is approx. 82 Kg. The strong and robust suspension and shocks are hall mark of this motorbike. Similarly, the stylish sporty visor, moulded fuel tank with embellished side covers further added the beauty of this motorcycle. <a href=\"https://www.facebook.com/ebike.pk/\">Atlas Honda Ltd&nbsp;</a>introduced 02 colors in <strong>Honda CD 70 Dream</strong> i.e. Black &amp; Red with stylish graphics.&nbsp;</p><p>The complete range of <a href=\"https://www.ebike.pk/used-bikes/bike-by-brand/honda/1\">Honda used bikes</a> available for sale in Pakistan.&nbsp;</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\"> <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\"></a></p>",
        "price": 129900,
        "engine": "4-Stroke OHC Air-Cooled",
        "boreAndStroke": "47.0 x 41.4 mm",
        "clutch": "Multiple wt Plates",
        "starting": "Kick Starter",
        "dimention": "1899 x 751 x 1014 mm",
        "petrolCapacity": "8.6 Liters",
        "displacement": "72 cm3",
        "compressionRatio": "8.8:1",
        "transmission": "Continuous 4 Speed Mesh",
        "frame": "Backbone Type",
        "groundClearance": "136 mm",
        "tyreBack": "2.50 – 17 (4 PR)",
        "tyreFront": "2.25 – 17 (4 PR)",
        "dryWeight": "\t82kg",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604378940/blogs/hfoosnf8fgrleqgzdb1p.jpg"
        ],
        "others": "",
        "bikeUrl": "honda-cd-70-dream",
        "videoUrl": "https://youtu.be/XLfsyP45htY",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-10T07:05:31.604Z",
        "updatedAt": "2023-01-30T06:45:44.043Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 6,
        "brandId": 1,
        "cityId": 1,
        "title": "Honda CB 125f ",
        "description": "<h2>Honda CB 125f</h2><p><strong>Honda CB 125f&nbsp;</strong>launched by <a href=\"https://www.ebike.pk/new-bikes/honda\">Atlas Honda Ltd</a>, the largest selling motorcycle assembler in Pakistan. Atlas Honda introduced CB 125f, keeping in view the fierce competition in <a href=\"https://www.ebike.pk/used-bikes/bike-by-cc/125/5\">125cc motorcycle segment&nbsp;</a>from Yamaha. The company has been enjoying the dominant position in 125cc motorcycles through Honda CG 125 for decades. Honda CG 125 has been popular in Pakistan due to its pickup and reliability. Though it doesn&rsquo;t have a sporty look.</p><p>Also Read <a href=\"https://www.ebike.pk/new-bikes/yamaha/yamaha-ybr-125/11\"></a> <a href=\"https://www.ebike.pk/new-bikes/honda/honda-cb-150f/7\">Honda CB150f</a></p><p>The introduction of <strong>Honda CB 125f&nbsp;</strong>provide user another option in 125cc motorcycle category with sporty look. In addition to this the bike also have a direct competition with all Yamaha models. Honda CB 125f is equipped with 04 stroke, air cooled, single cylinder OHV engine. &nbsp;The bike has 56.6mm bore and 59.5mm stroke. Honda CB 125F has 5 speed transmission and a self-start option along with kickstart. The fuel tank capacity of this motorcycle is 12.3 Liters whereas dry weight of the bike is 122 Kg.&nbsp;</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\"> <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\"></a></p>",
        "price": 283900,
        "engine": "4 Stroke 125cc OHV  Air Cooled Engine",
        "boreAndStroke": "56.6 x 59.5 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Self-Start/Kick Start",
        "dimention": "2043 x 742 x 1095 mm",
        "petrolCapacity": "12.3 Liters (Reserve 2.7 Liters)",
        "displacement": "124.1 cm3",
        "compressionRatio": "9.0:1",
        "transmission": "Continuous 5 Speed Mesh",
        "frame": "Backbone Type",
        "groundClearance": "120 mm",
        "tyreBack": "90/90 – 18M/C (51S)",
        "tyreFront": "2.75 – 18M/C (42P)",
        "dryWeight": "122kg",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1606482204/blogs/d9amvug6qu2lrzdnhtca.jpg"
        ],
        "others": "",
        "bikeUrl": "honda-cb-125f",
        "videoUrl": "",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-10T07:42:18.121Z",
        "updatedAt": "2023-01-30T06:41:59.191Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 7,
        "brandId": 1,
        "cityId": 1,
        "title": "Honda CB 150f ",
        "description": "<h2>Honda CB 150f</h2><p><strong>Honda CB150f&nbsp;</strong>is an excellent sporty design motorcycle, considering the growing demand of 150cc motorcycles in Pakistan. The motorcycle is equipped with 04 stroke 150cc SOHC engine with 05 gear transmission and self-start option. It has a strong, reliable and powerful shocks allow riders a comfortable ride even on long journeys.</p><p>Also Read <a href=\"https://www.ebike.pk/new-bikes/honda/honda-cb-250f/8\">Honda CB 250f</a></p><p><strong>Honda CB 150f&nbsp;</strong>has a sporty fuel tank with well design graphics. Furthermore, the specially designed Z Section die casted alloys rims make CB 150f more attractive and appealing to its users. The company ensure maximum safety for its riders by installing powerful front disc brakes. Moreover, it has a special design low maintenance viscous air filter considering the dusty environment. It also has a stylish fuel gauge, gear indicator, trip meter, impressive LED supported Tail Light, stylish and Aerodynamic muffler. The introduction of Honda CB 150f in <a href=\"https://www.ebike.pk/used-bikes/bike-by-cc/150/6\">150cc motorcycle segment</a> allows the users a good reasonable choice from leading motorcycle manufacturer.</p><p><a href=\"https://www.ebike.pk/used-bikes/bike-by-brand/honda/1\">Honda Used Motorcycle</a> are available for sale in Pakistan</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\"> <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\"></a></p>",
        "price": 327900,
        "engine": "4 Stroke 150cc SOHC  Air Cooled Engine with Balancer",
        "boreAndStroke": "57.3 x 57.8 mm",
        "clutch": "Wet Type Multi-Plate",
        "starting": "Self-Start/Kick Start",
        "dimention": "2051 x 760 x 1085 mm",
        "petrolCapacity": "13.0 Liters (Reserve 1.4 Liters)",
        "displacement": "149.2 cm3",
        "compressionRatio": "9.1:1",
        "transmission": "Continuous 5 Speed Mesh",
        "frame": "Backbone Type",
        "groundClearance": "168 mm",
        "tyreBack": "90/90 – 18M/C (51P)",
        "tyreFront": "80/100 – 18M/C (47P)",
        "dryWeight": "124kg",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604561829/blogs/ywgx4ri2jmfhmdtijnyd.jpg"
        ],
        "others": "",
        "bikeUrl": "honda-cb-150f",
        "videoUrl": "https://youtu.be/gdNHZDTg6x8",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-10T08:20:07.189Z",
        "updatedAt": "2022-08-18T08:12:36.575Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 210,
        "brandId": 1,
        "cityId": 1,
        "title": "Honda CG 125s Special Edition",
        "description": "<h2>Honda CG 125S</h2><p dir=\"ltr\"><strong>Honda CG 125S</strong> special edition is the classic bike, it&rsquo;s 4 Stroke 125cc OHV (Overhead valve) Air Cooled generates enormous power with a compression ratio of 9 : 1 and displacement of 124.1 cc. The model comes with 5 Speed Constant Mesh transmission and Self-Start / Kick Start options.&nbsp;</p><p dir=\"ltr\">Also Read: <a href=\"https://www.ebike.pk/new-bikes/honda/honda-cb-125f/6\"></a><a href=\"https://www.ebike.pk/new-bikes/yamaha/yamaha-ybr-125/11\">Yamaha YBR125</a>&nbsp;</p><p dir=\"ltr\"><strong>Honda CG 125S&nbsp;</strong>stock comes with a rear Swing Arm 70mm Travel suspension hooked up with 3.00-17 (50P) tyre and front <a href=\"https://en.wikipedia.org/wiki/Telescopic_fork\">Telescopic Fork 103mm&nbsp;</a>Travel suspension hooked up with 2.50-18 (38P) tyre, which provides a smooth and safe riding experience to its users.</p><p dir=\"ltr\">The special edition gives Modern Black Painted Muffler Exhaust with Breathtaking Sounds and Huge Rear Wheel Drum which adds esthetics to CG125.</p><p dir=\"ltr\">The complete <a href=\"https://www.ebike.pk/used-bikes/bike-by-brand/honda/1\">Honda Used Bike range available for sale</a>.</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\"> <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\"></a></p>",
        "price": 219900,
        "engine": "4 Stroke 125cc OHV Air Cooled Engine",
        "boreAndStroke": "56.5 x 49.5 mm",
        "clutch": "Constant Mesh",
        "starting": "Kick & Electric Start",
        "dimention": "1912",
        "petrolCapacity": "9.2 L",
        "displacement": "124 cc",
        "compressionRatio": "9.0:1",
        "transmission": "5-speed",
        "frame": "Diamond Steel Type",
        "groundClearance": "133 mm",
        "tyreBack": "3.00 - 17\t",
        "tyreFront": "2.50 - 18",
        "dryWeight": "108 KG",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604561323/blogs/eiydolmpqhqjfzym52de.jpg"
        ],
        "others": "",
        "bikeUrl": "honda-cg-125s-special-edition",
        "videoUrl": "https://youtu.be/j81qeUb58iI",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-03-18T09:30:46.581Z",
        "updatedAt": "2023-01-30T06:49:26.229Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 5,
        "brandId": 1,
        "cityId": 1,
        "title": "Honda CG 125",
        "description": "<h2>Honda CG 125</h2><p><strong>Honda CG 125</strong>, the market leader in 125 cc motorcycle segment in Pakistan for decades. The production of CG 125 started in 1976 and continued till 2008 throughout the world. However, it is still continued in Pakistan with slight changes. Honda 125 CC is equipped with 124cc (7.6 cu in) four stroke, ohv, single cylinder engine. The other variant of Honda Cg 125 is available in self start.</p><p>Also Read: <a href=\"https://www.ebike.pk/new-bikes/honda/honda-cb-125f/6\">Honda CB 125f</a><a href=\"https://www.ebike.pk/new-bikes/yamaha/yamha-ybr-125g/9\"></a><a href=\"https://www.ebike.pk/new-bikes/honda/honda-cb-125f/6\" rel=\"noopener noreferrer\" target=\"_blank\"></a></p><p><strong>Honda CG 125</strong> is equipped with Euro II technology. The robust engine and their powerful shocks provide riders a riding pleasure. <a href=\"https://www.ebike.pk/new-bikes/honda\">Honda&nbsp;</a>125 12 Liter fuel tank ensures the riders to continue their long journey. Recently Atlas Honda also introduced Honda CB 125 F. So far Honda CG 125 is the market leader in <a href=\"https://powersports.honda.com/street/minimoto/super-cub-c125\">125 cc motorcycle&nbsp;</a>segment due to its reliability and pickup.</p><p>Atlas Honda Pakistan, the assembler of Honda 125 motorcycles has started &nbsp;changes the bike prices in Pakistan very frequently.</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\"> <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\"></a></p>",
        "price": 185900,
        "engine": "4-Stroke OHV Cooled by Air",
        "boreAndStroke": "56.5 x 49.5 mm",
        "clutch": "N/A",
        "starting": "Kick Start",
        "dimention": "1912 x 735 x 1026 mm",
        "petrolCapacity": "9.2 Liters (Reserve 2 Liters)",
        "displacement": "125 cc",
        "compressionRatio": "9.0:1",
        "transmission": "Continuous 4 Speed Mesh",
        "frame": "Diamond Type Steel",
        "groundClearance": "132 mm",
        "tyreBack": "3.00 – 17 (6 PR)",
        "tyreFront": "2.50 – 18 (4 PR)",
        "dryWeight": "100kg",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604561899/blogs/klkk4hite8yfdrmm7rlv.jpg"
        ],
        "others": "",
        "bikeUrl": "honda-cg-125",
        "videoUrl": "https://youtu.be/a70kTxtwN_k",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-10T07:31:06.753Z",
        "updatedAt": "2023-01-30T06:44:28.731Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 3,
        "brandId": 1,
        "cityId": 1,
        "title": "Honda Pridor 100 ",
        "description": "<h2>Honda Pridor 100</h2><p><strong>Honda Pridor</strong> 2022 yet another quality motorcycles introduced by none other than Atlas Honda Limited. Honda Pridor is introduced to meet the growing demand of <a href=\"https://www.ebike.pk/used-bikes/bike-by-cc/100/3\">100cc motorcycle</a> segment. Atlas Honda is known for introducing quality and reliable motorcycles in Pakistan. AHL is a joint venture between Honda Corporation and Atlas Group.</p><p>Also Read: <a href=\"https://www.ebike.pk/new-bikes/honda/honda-cg-125/5\">Honda CG125</a><a href=\"https://www.ebike.pk/new-bikes/honda/honda-cg-125/5\"></a><a href=\"https://www.ebike.pk/new-bikes/honda/honda-cg-125/5\"></a></p><p><a href=\"https://www.ebike.pk/new-bikes/honda\">Honda</a> Pridor has an aerodynamic design and it is equipped with 04 stroke air cooled OHV engine with stylish and beautiful indicators. <strong>Honda Pridor</strong> is known for its quality and reliability. It has strong and robust engine with powerful shock absorber that provide rider a comfortable ride even on rough road.&nbsp;</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\"> <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\"></a></p>",
        "price": 161900,
        "engine": "4-Stroke OHC Air-Cooled Single Cylinder",
        "boreAndStroke": "50.0 x 49.5 mm",
        "clutch": "N/A",
        "starting": "Kick Starter",
        "dimention": "1986 x 718 x 1050 mm",
        "petrolCapacity": "9.7 Liters (Reserve 1.5 Liters)",
        "displacement": "97.1 cm3",
        "compressionRatio": "9.0:1",
        "transmission": "4-Speed Constant Mesh",
        "frame": "Double Cradel",
        "groundClearance": "156 mm",
        "tyreBack": "2.75 – 18 (6 PR)",
        "tyreFront": "2.75 – 18 (4 PR)",
        "dryWeight": "96kg",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/dtroqldun/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1604561978/blogs/tefqf5cpjqg9fcvglfpf.jpg"
        ],
        "others": "",
        "bikeUrl": "honda-pridor",
        "videoUrl": "https://youtu.be/sznFjwX0bg0",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2019-01-10T07:21:59.415Z",
        "updatedAt": "2023-01-30T06:45:21.272Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    },
    {
        "id": 225,
        "brandId": 1,
        "cityId": 1,
        "title": "Honda CD 70",
        "description": "<p><strong>Honda CD70</strong>, the largest selling motorcycle brand in Pakistan. CD70 started its journey in 1976 and since than it has become a symbol of success in the motorcycle industry of Pakistan. The purpose of this motorcycle is to cater the need of masses through economical bike</p><p>Also Read: <a href=\"https://www.ebike.pk/new-bikes/honda/honda-cg-125/5\" rel=\"noopener noreferrer\" target=\"_blank\">Honda cg 125</a></p><p><strong>Honda CD70</strong> is equipped with 04 stroke single cylinder air cooled engine and has 8.5 ltr fuel tank. Ever since its inception the motorcycle has been the same except for little changes in fuel tank sticker and speedo meter. Atlas Honda Ltd, the manufacturer of this bike has been dominating in the motorcycle segment mainly due to CD70.</p><p>Honda CD70 is popular among the masses mainly due to its fuel efficiency and easily available economical spare parts. The bike is available in 03 colors.</p><p data-f-id=\"pbf\" style=\"text-align: center; font-size: 14px; margin-top: 30px; opacity: 0.65; font-family: sans-serif;\"> <a href=\"https://www.froala.com/wysiwyg-editor?pb=1\" title=\"Froala Editor\"></a></p>",
        "price": 157900,
        "engine": "4-Stroke OHC Air-Cooled",
        "boreAndStroke": "47.0 x 41.4 mm",
        "clutch": "Multiple Wet Plates",
        "starting": "Kick Start",
        "dimention": "1897 x 751 x 1014 mm",
        "petrolCapacity": "8.5 Liters",
        "displacement": "72 cm3",
        "compressionRatio": "8.8:1",
        "transmission": "4 speed constant mesh",
        "frame": "Backbone Type",
        "groundClearance": "136mm",
        "tyreBack": "2.50 - 17 (4 PR)",
        "tyreFront": "2.25 - 17 (4 PR)",
        "dryWeight": "82 kg",
        "uid": "f6882342-689b-41a7-b142-446512ff158f",
        "images": [
            "http://res.cloudinary.com/ic-solutions/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1714649546/new-bikes/zrwhqiaa5lm2oajf2x6w.jpg",
            "http://res.cloudinary.com/ic-solutions/image/upload/c_scale,dpr_auto,f_auto,q_auto,w_auto/v1714818974/new-bikes/qx0iks6gyuxqxkfjbfiz.jpg"
        ],
        "others": "",
        "bikeUrl": "honda-cd-70",
        "videoUrl": "https://www.youtube.com/watch?v=TTfFm8fI3VY",
        "meta_title": "",
        "meta_description": "",
        "focus_keyword": "",
        "createdAt": "2020-11-05T06:50:05.188Z",
        "updatedAt": "2024-05-04T10:39:04.087Z",
        "bike_brand": {
            "id": 1,
            "brandName": "honda",
            "logoUrl": "https://res.cloudinary.com/dtroqldun/image/upload/c_scale,f_auto,h_50,q_auto,w_auto,dpr_auto/v1540624358/bike_brands/Honda.png",
            "description": "Atlas Honda limited first lay it’s foundation on 16th of October 1962 and proved to be a well-known public limited company. The company is a joint collaboration between Honda Motors Limited, which is a renowned motorcycle brand in the world, and The Atlas group which is Pakistan’s most well reputed business conglomerates. Atlas Honda is known to be the largest assembler of motorcycles and enjoys the position of being the market leader in the industry. \n\n\nThe company believes in progressive manufacturing and has engaged itself in progressive and up to date methods of marketing of motorcycles and their parts. Atlas Honda therefore has the strongest brand reputation and remarkable loyalty received from their customers. The brand has over the years created an image that is now nearly impossible to shatter and hence increased competitiveness. \n\n\nConsidered the pioneers of the motorcycle industry Atlas Honda has successfully covered fifty years into the dynamic industry without failure. As for now the company has a large production capacity, approximately about 1.35 million units per year. Atlas Honda refused to stay back in any field and is also an exporter of its motorcycles including their spare parts to countries like Afghanistan and Bangladesh. \n\n\nOwning state of the art manufacturing tools and facilities as well as having the highest quality products and not to forget their after sales services, the company has created the benchmark for manufacturing motorcycles. \n\n\nProudly Atlas Honda has set the bar so high for the rest of the industry that it is hard for others to compete with the capabilities and professionalism of the company. Being one of the largest tax payers and market leaders in the private sector, Atlas Honda provides amazing employment opportunities. The company proves to be a mentor for all sectors of the industry. ",
            "vediourl": null,
            "meta_title": "",
            "meta_description": "Honda New Bikes in Pakistan, Get yourself updated from latest news and videos reviews about Honda New Bikes CD 70, CG 125, CB 125F, CG125S, CB150f, CB250f",
            "focus_keyword": "honda",
            "createdAt": "2018-12-14T12:18:45.057Z",
            "updatedAt": "2019-11-06T07:43:18.264Z"
        },
        "city": {
            "id": 1,
            "city_name": "Karachi",
            "createdAt": "2018-11-08T16:19:57.658Z",
            "updatedAt": "2018-11-08T16:19:57.658Z"
        }
    }
]
export default BikePriceData